### ISSUE TITLE
Unit tests should only test exported API methods

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [gsproston-scottlogic/prompt-injection#346]
## Description
Currently we are exporting several functions for the sake of testing, even if they are only being used internally inside a module. The golden rule is, only test the API of a module. If you then find you need too much setup in your tests, then likely the module is doing too much, and is a candidate for splitting into different responsibilities.

## Tasks
I'm thinking it's best to split this ticket up as the changes can be quite large and it'll be easier to review them per file imo.

Existing files (some might not be applicable):

- [x] app.ts **- N/A, just exports app**
- [x] #641
- [x] #648
- [x] #649
- [x] importMetaUtils.ts **- N/A**
- [x] #650
- [x] #651
- [x] promptTemplate.ts **- N/A, just exports static strings**
- [x] router.ts **- N/A, just exports the router**
- [x] server.ts **- N/A, no exports**

## AC
This is a refactor ticket, so just regression testing here.
