### ISSUE TITLE
Level does not pass for correct email sent when we fail to get chatGPT reply

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [gsproston-scottlogic/prompt-injection#467]
I was completing level 1. I got the win condition by sending an email to bob with the word "brae" in it. However because something went wrong with the link to the openAI api, I did not pass the level. I think we could alter the the logic to check the win condition to account for this unlikely situation.

This is a very minor and hard to reproduce issue

![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/afbbe975-ba3c-439c-b60e-0d136737b139)

## Tasks

- [ ] Pass the level when this happens
- [ ] Change the error text to "Failed to get reply"
- [ ] Alter UI to make it more obvious that this is an error message

## AC

GIVEN the bot has sent an email which passes the level
AND the next GPT call fails
WHEN the frontend gets the response
THEN the level is passed
AND the sent email is shown
AND an error message is shown with the text "Failed to get reply"

GIVEN the bot has NOT sent an email which passes the level
AND the next GPT call fails
WHEN the frontend gets the response
THEN the level is NOT passed
AND an error message is shown with the text "Failed to get reply"
