### ISSUE TITLE
Correct DefenceBox callbacks to clean up config reset

### ISSUE THREAD

**Issue by chriswilty** [gsproston-scottlogic/prompt-injection#548]
## Description

In PR #533 we added a workaround for a bug in which clearing a defence config input then clicking reset would not actually reset the input value.

This led to some diving into the component structure....

```
MainComponent =>
  MainBody =>
    ControlPanel =>
      DefenceBox =>
        DefenceMechanism =>
          DefenceConfiguration =>
            DefenceConfigurationInput
```

- Defences to show (DefenceInfo array) in the panel are stored as state in MainComponent
- These are then passed down through MainBody into ControlPanel
- Here they are filtered into two sublists: model defences and prompt defences, and each passed into a DefenceBox component
- DefenceBox then renders a DefenceMechanism for each defence
- DefenceMechanism defines a function `resetDefenceConfiguration` which invokes an API call, which resets the given config in the session store and returns its default value; this default value is then returned from the resetDefenceConfiguration function (which is unusual for a callback function prop - usually they return void).
- DefenceMechanism passes the above function into DefenceConfiguration component, along with another callback function: setConfigurationValue
- DefenceConfiguration renders the Reset button, which on click calls resetDefenceConfiguration, captures the returned value, and then calls setConfigurationValue callback prop with that value.
- setConfigurationValue function starts by validating the value (which we know is valid!) and then calls setDefenceConfiguration callback prop, which is actually defined in MainComponent and drilled down through three intermediate components.
- setDefenceConfiguration invokes an API call to set the given config - which we know was already set, and returned to us, in the earlier API call.
- On (successful) response, the defences are updated in MainComponent, and then filter all the way back down the component hierarchy into DefenceConfigurationInput.

DefenceConfigurationInput holds its own state value for the current value, because this needs to be changed and submitted by the user. On mount, and then whenever the config value has been changed via an API call, this state value is reset to the value of prop `defaultValue`. This should work just fine, so the workaround is clearly masking a bigger problem. Hopefully solving the above double-API call will resolve the issue correctly.

## Tasks

- [x] Define a callback function "resetDefenceConfiguration" in MainComponent and pass it all the way down to DefenceMechanism component. This callback should invoke the resetDefenceConfig service call, and update the defences state on success, same as is done in setDefenceConfiguration
- [x] Modify function resetConfigurationValue in DefenceMechanism to invoke the above callback instead of calling the API service directly.
- [x] Change name of DefenceConfigurationInput prop "defaultValue" to something like "currentValue", to better reflect its purpose.
- [x] Change the dependency array of the useEffect to [currentValue].
- [x] Test it out....

## AC
Regression, makes sure everything still works. Especially resetting defences.
